## NumPy library

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print(array1)

[1 2 3]


In [ ]:
array2 = np.zeros(5)
print(array2)

[0. 0. 0. 0. 0.]


In [ ]:
array3 = np.ones(5)
print(array3)

[1. 1. 1. 1. 1.]


In [ ]:
array4 = np.empty(3) # مصفوفه من بيانات عشوائيه.. غير مهيئه
print(array4)

[1. 1. 1.]


In [ ]:
array5 = np.arange(5)
print(array5)

[0 1 2 3 4]


In [ ]:
array6 = np.arange(0, 25, 5)
print(array6)

[ 0  5 10 15 20]


In [ ]:
# Array of equal points
array7 = np.linspace(0, 36, 9)
print(array7)

[ 0.   4.5  9.  13.5 18.  22.5 27.  31.5 36. ]


In [ ]:
oned = np.arange(21)
print(oned, '\n')

print(oned.dtype)
print(oned.size)
print(oned.nbytes)
print(oned.shape)
print(oned.ndim) # ndim هو خاصية (attribute) تُستخدم للحصول على عدد الأبعاد (dimensions) للكائن. فمثلاً، إذا كانت oned مصفوفة ثنائية الأبعاد، فإن oned.ndim ستعيد القيمة 2.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

int64
21
168
(21,)
1


كيفية معرفة عدد أبعاد المصفوفه https://monica.im/home/chat/Monica/monica?convId=conv%3A1c1a19a1-fe69-441f-a24c-447e008a62c2

In [ ]:
type(oned) # n-dimensional array

numpy.ndarray

In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(matrix, '\n')
print(matrix.shape, '\n')
print(matrix.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

(4, 4) 

2


In [ ]:
reshaped_1d = matrix.reshape(16)
print(reshaped_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
reshaped_2d = matrix.reshape(2, 8)
print(reshaped_2d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
new_array = matrix.reshape(2, 2, 2, 2)
print(new_array)
print('\n الشكل', new_array.shape)
print('عدد الأبعاد',new_array.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

 الشكل (2, 2, 2, 2)
عدد الأبعاد 4


In [ ]:
print(matrix.reshape(3, 3)) # read the error text, and you will understand

ValueError: cannot reshape array of size 16 into shape (3,3)

In [ ]:
matrix.reshape(3, 3)

ValueError: cannot reshape array of size 16 into shape (3,3)

### Indexing and clicing in NumPy

In [ ]:
# الفهرسه والتقطيع في نمباي

In [ ]:
import numpy as np

one = np.arange(10)
print(one)
print(one[-1])
print(one[3])
print(one[:5])
print(one[2:-3])

In [ ]:
two = np.arange(21).reshape(3, 7)
print(two, '\n')

print(two[1])
print(two[1, 3])
print(two[:, 3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] 

[ 7  8  9 10 11 12 13]
10
[ 3 10 17]


In [ ]:
two[1, 3] = 100
print(two)

[[  0   1   2   3   4   5   6]
 [  7   8   9 100  11  12  13]
 [ 14  15  16  17  18  19  20]]


In [ ]:
two[1:, 4:] = 0
print(two)

[[  0   1   2   3   4   5   6]
 [  7   8   9 100   0   0   0]
 [ 14  15  16  17   0   0   0]]


In [ ]:
list1 = [1, 2, 3, 4, 5] * 0
print(list1)

[]


In [ ]:
list2 = [1, 2, 3, 4, 5]
s = list2 * 0
print(s)

[]


In [ ]:
res = [1, 2, 3] * [4, 5, 6] # لا يمكن ضرب قائمتين.. حتى لو كانتا بنفس الطول.. سنحصل على خطأ
print(res)

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
array8 = np.array([1, 2, 3])
array9 = np.array([4, 5, 6])
print(array8 * array9)
print(array8 + array9)
print(array8 - array9)
print(array8 / array9)

[ 4 10 18]
[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [ ]:
import numpy as np

mask = np.ones_like(True, shape=(3, 7))
print(mask)

[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [ ]:
mask[1:,:] = False
print(mask)

[[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
import numpy as np

maskkk = np.ones_like(True, shape=(4, 4))
maskkk[2:, :] = False
print(maskkk)

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]


In [ ]:
##############
two = np.arange(21).reshape(3, 7)
print(two)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [ ]:
mask = np.ones_like(True, shape=(3, 7))
mask[1:, :] = False
print(mask)

[[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
print('Filtered array:',two[mask])

Filtered array: [0 1 2 3 4 5 6]


In [ ]:
##############

In [ ]:
r = two < 5
print(r)

[[ True  True  True  True  True False False]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
Filtered_values = two[two < 5]
print(Filtered_values)

[0 1 2 3 4]


In [ ]:
complex_condition = two[(two < 5) & (two % 2 == 0)]
print(complex_condition)

[0 2 4]


In [ ]:
import numpy as np

mask = np.ones_like(True, shape=(3, 7))
mask[1:, :] = False
print("Mask:\n", mask)

Mask:
 [[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
two = np.array([[33, 1, 2, 3, 4, 5, 6],
                [0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0]])

print(two[mask])

[33  1  2  3  4  5  6]


In [ ]:
result_mask = two < 5
print(result_mask)

[[False  True  True  True  True False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [ ]:
filtered_values = two[result_mask]
print(filtered_values)

[1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
filtered_values = two[two < 5]
print(filtered_values)

[1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
# complex_condition

complex_condition = two[(two < 5) & (two % 2 == 0)]
print(complex_condition)

[2 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
import numpy as np

mask = np.ones_like(True, shape=(3, 7))
mask[1:, :] = False
print(mask)

[[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
two = np.array([[33, 1, 2, 3, 4, 5, 6],
                [0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0]])

print(two[mask])

[33  1  2  3  4  5  6]


In [ ]:
s = two < 0
print(s)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
d = two > 1
d

array([[ True, False,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [ ]:
f = d
print(f)

[[ True False  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


### التمثيلات والنسخ في NumPy

In [ ]:
import numpy as np

a = np.arange(24).reshape(4, 6)
print('Array A: \n', a)

Array A: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
b = a[:2, 3:]
print(b)

[[ 3  4  5]
 [ 9 10 11]]


In [ ]:
b[1, 1] = 55
print('Array B:\n', b)

Array B:
 [[ 3  4  5]
 [ 9 55 11]]


In [ ]:
# Create a copy of b

b = a[:2, 3:].copy()
print('Array B (copy): \n', b)

Array B (copy): 
 [[ 3  4  5]
 [ 9 55 11]]


In [ ]:
# Modify an element in the copy

b[1, 1] = -1
print(b)

[[ 3  4  5]
 [ 9 -1 11]]


In [ ]:
print(a, '\n')
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 55 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[ 3  4  5]
 [ 9 -1 11]]


### طرق المصفوفة في NumPy - Методы массива

In [ ]:
import numpy as np

data = np.arange(12).reshape(3, 4)
print('data:\n', data, '\n')

print(data.min())
print(data.max())
print(data.sum())
print(data.mean())
print(data.std()) # Standard deviation
print(data.sum(1))
print(data.sum(0))
print(data.argmax(1))
print(data.argmax(0))

data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

0
11
66
5.5
3.452052529534663
[ 6 22 38]
[12 15 18 21]
[3 3 3]
[2 2 2 2]


In [ ]:
A1 = np.arange(9).reshape(3, 3)
print('A1:\n', A1)
print('\n Transposed A:\n', A1.T) # Transpose

A2 = np.ones(9).reshape(3, 3)
print('\n A2:\n', A2)
print('\n A1 @ A2:\n', A1 @ A2) # Matrix multiplication

print('\n Dot product:\n', A1.dot(A2)) # Dot product
print('\n Diagonal of the matrix:\n', A1.diagonal()) # Diagonal of the matrix

A1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 Transposed A:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

 A2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 A1 @ A2:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]

 Dot product:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]

 Diagonal of the matrix:
 [0 4 8]


In [ ]:
print(A1.dtype)
print(A1.size)
print(A1.nbytes, '\n')

# Create an array with int8 type
# C = np.arange(9).reshape(3, 3)  # dtype == int16
C = np.arange(9, dtype=np.int8).reshape(3, 3)
print(C)
print('\n', C.dtype)
print('\n', C.nbytes)

int64
9
72 

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 int8

 9


In [ ]:
# تحويل البيانات

C[1, 1] = 0.5
print(C[1, 1])

0


البث في بايثون Broadcasting

In [6]:
import numpy as np

A1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A2 = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])

print('Result:')
print('A1:\n', A1)
print('A2:\n', A2)
print(f'A1 {A1.shape} + A2 {A2.shape} = A3 {(A1 + A2).shape}:\n', A1 + A2)

Result:
A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
A1 (3, 3) + A2 (3, 3) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
